### ISSUE TITLE
Add README covering branches and links to videos

### ISSUE THREAD

**Issue by eliassal** [dockersamples/mta-netfx-dev#6]
Elton, there is no single file of code

**Comment by eliassal** [comment]
Also when trying dockr.ly/windows, I land nowhere, thanks for your help

**Comment by sixeyed** [comment]
There are branches for each part of the video, e.g. https://github.com/dockersamples/mta-netfx-dev/tree/part-5 takes you to the exact code I use in Part 5, and there's `part-1`, `part-2` etc.

If you want your own copy of the code, do this:

```
git clone https://github.com/dockersamples/mta-netfx-dev.git
git checkout part-4 # or whatever
```

Leaving issue open because I do need to put this in a README :)

Also, I've fixed the link: https://dockr.ly/windows - thanks for reporting!

**Comment by eliassal** [comment]
Thanks

**Comment by eliassal** [comment]
Elton I did "git clone https://github.com/dockersamples/mta-netfx-dev.git", worked fine but running 

git checkout part-1 #
gives the following error

> fatal: Not a git repository (or any of the parent directories): .git

**Comment by sixeyed** [comment]
You need to `cd mta-netfx-dev`. Updated the instructions above.

**Comment by eliassal** [comment]
Great, yes it works like a charm now

**Comment by eliassal** [comment]
Elton, I have docker on windows not docker for windows. The version is 

> Client:
>  Version:      1.13.0-dev
>  API version:  1.25
>  Go version:   go1.7.3
>  Git commit:   96efb2c
>  Built:        Mon Oct 24 15:30:23 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.13.0-dev
>  API version:  1.25
>  Go version:   go1.7.3
>  Git commit:   96efb2c
>  Built:        Mon Oct 24 15:30:23 2016
>  OS/Arch:      windows/amd64

It seems that this version does not allow Multi-Stage build, is that correct? if yes any idea on how to upgrade docker on wins

**Comment by eliassal** [comment]
Elton, I managed to upgrade my docker version and was able to run the 1st command but halfway getting "unauthorized: authentication required" as you can notice hereunder

> 
> \mta-netfx-dev> docker image build `
> >> --tag dockersamples/mta-dev-signup-app:v1 `
> >> --file .\docker\web\Dockerfile .
> Sending build context to Docker daemon  2.471MB
> Step 1/10 : FROM dockersamples/mta-dev-web-builder:3.5 AS builder
> 3.5: Pulling from dockersamples/mta-dev-web-builder
> 3889bb8d808b: Already exists
> 449343c9d7e2: Downloading [=================================================> ]  1.302GB/1.304GB
> f469e339ce37: Download complete
> 4569602ec5f7: Download complete
> d9598bb7e5f2: Download complete
> 0ffe12052320: Downloading [======================>                            ]    346MB/771.1MB
> 0296e953b7cb: Downloading
> f14b2dcaeed6: Waiting
> 28de7c470755: Waiting
> d1ae3c6440cd: Waiting
> 69523c6a8634: Waiting
> dc39c09bb038: Waiting
> 96b26429c168: Waiting
> 32f3c499b64d: Waiting
> b46699b14ca5: Waiting
> **unauthorized: authentication required**
